version: '3'
services:
  web:
    restart: always
    build: .
    image: protein-searcher_web:latest
    command: "bin/docker_init"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
  rq:
    restart: always
    image: protein-searcher_web:latest
    command: "bin/run_rq"
    volumes:
      - .:/usr/src/app
    depends_on:
      - web
  redis:
    restart: always
    image: "redis:alpine"
    ports:
      - "6379:6379"
