version: '3'
services:
  ui:
    container_name: ui
    build: ./ui
    ports:
      - "80:80"
    links:
      - api
    depends_on:
      - api
  api:
    restart: always
    build: .
    image: protein-searcher_api:latest
    command: "bin/docker_init"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
  rq:
    restart: always
    image: protein-searcher_api:latest
    command: "bin/run_rq"
    volumes:
      - .:/usr/src/app
    depends_on:
      - api
  redis:
    restart: always
    image: "redis:alpine"
    ports:
      - "6379:6379"
