version: '3'
services:
  web:
    restart: always
    build: .
    command: "bin/docker_init"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    restart: always
    image: "redis:alpine"
