# Generated by Django 2.2 on 2019-06-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('code', models.CharField(max_length=32)),
                ('sequence_file_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='search',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
