# Generated by Django 2.2 on 2019-06-09 19:03

from django.core.management import call_command
from django.db import migrations

PROTEINS = [
    {
        'name': 'Paramecium bursaria Chlorella virus 1',
        'code': 'NC_000852',
        'sequence_file_name': 'NC_000852.gb'
    },
    {
        'name': 'Emiliania huxleyi virus 86',
        'code': 'NC_007346',
        'sequence_file_name': 'NC_007346.gb'
    },
    {
        'name': 'Acanthocystis turfacea Chlorella virus 1',
        'code': 'NC_008724',
        'sequence_file_name': 'NC_008724.gb'
    },
    {
        'name': 'Paramecium bursaria Chlorella virus AR158',
        'code': 'NC_009899',
        'sequence_file_name': 'NC_009899.gb'
    },
    {
        'name': 'Cafeteria roenbergensis virus BV-PW1',
        'code': 'NC_014637',
        'sequence_file_name': 'NC_014637.gb'
    },
    {
        'name': 'Acanthamoeba polyphaga moumouvirus',
        'code': 'NC_020104',
        'sequence_file_name': 'NC_020104.fasta'
    },
    {
        'name': 'Pithovirus sibericum isolate P1084-T',
        'code': 'NC_023423',
        'sequence_file_name': 'NC_023423.gb'
    },
    {
        'name': 'Megavirus chiliensis',
        'code': 'NC_016072',
        'sequence_file_name': 'NC_016072.gb'
    },
    {
        'name': 'Bacillus phage G',
        'code': 'NC_023719',
        'sequence_file_name': 'NC_023719.gb'
    },
    {
        'name': 'Mollivirus sibericum isolate P1084-T',
        'code': 'NC_027867',
        'sequence_file_name': 'NC_027867.gb'
    }
]

def load_proteins(apps, schema_editor):
    Protein = apps.get_model("api", "Protein")
    for seed_data in PROTEINS:
        protein = Protein(**seed_data)
        protein.save()

def unload_proteins(apps, schema_editor):
    Protein = apps.get_model("api", "Protein")
    Protein.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190609_1902'),
    ]

    operations = [
        migrations.RunPython(load_proteins, reverse_code=unload_proteins),
    ]
