# Generated by Django 2.2 on 2019-06-09 19:03

from django.core.management import call_command
from django.db import migrations

def up(apps, schema_editor):
    protein = get_protein(apps)
    protein.sequence_file_name = 'NC_016072.fasta'
    protein.save()

def down(apps, schema_editor):
    protein = get_protein(apps)
    protein.sequence_file_name = 'NC_016072.gb'
    protein.save()

def get_protein(apps):
    Protein = apps.get_model("api", "Protein")
    return Protein.objects.get(code='NC_016072')

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_result'),
    ]

    operations = [
        migrations.RunPython(up, reverse_code=down),
    ]
