# Generated by Django 2.2 on 2019-06-10 02:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('api', '0006_auto_20190610_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='session',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
            preserve_default=False,
        ),
    ]
